# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=64)),
                ('f2', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Child1',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelapp1.Parent')),
                ('f3', models.CharField(max_length=64)),
                ('f4', models.CharField(max_length=64)),
            ],
            bases=('modelapp1.parent',),
        ),
        migrations.CreateModel(
            name='Child2',
            fields=[
                ('child1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelapp1.Child1')),
                ('f5', models.CharField(max_length=64)),
            ],
            bases=('modelapp1.child1',),
        ),
    ]
