# Generated by Django 2.2.6 on 2019-12-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('govtid', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=256)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField()),
                ('ac_rno', models.IntegerField(default=None)),
                ('vip_rno', models.IntegerField(default=None)),
            ],
        ),
    ]
