# Generated by Django 2.2.6 on 2019-12-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ac_rno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='vip_rno',
            field=models.IntegerField(),
        ),
    ]
