# Generated by Django 2.2.6 on 2019-12-21 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20191221_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
    ]
